x1 = int(input("enter the number of x1 :"))
x2 = int(input("enter the number of x2 :"))
y1 = int(input("enter the number of y1 :"))
y2 = int(input("enter the number of y2 :"))
slope=(y2-y1)/(x2-x1)
print("slope is ",slope)